anthropic_key = input("Paste Anthropic key: ")
elevenlabs_key = input("Paste ElevenLabs key: ")
f = open('/Users/regulatorsnation/Desktop/focus/focus_app.py', encoding='utf-8')
content = f.read()
f.close()
content = content.replace('your-api-key-here', anthropic_key.strip())
content = content.replace('your-elevenlabs-key-here', elevenlabs_key.strip())
f = open('/Users/regulatorsnation/Desktop/focus/focus_app.py', 'w', encoding='utf-8')
f.write(content)
f.close()
print("Both keys saved!")
